name: Build and Release AppImage

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: |
          sudo apt-get install -y wget
          # Install AppImage dependencies
          sudo apt-get install fuse libfuse2

      - name: Build AppImage
        run: deno run --allow-all scripts/appImage.ts

      - name: Get commit hash
        id: commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: ./Virtual_Microphone-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
